NORMALIZATION PROBLEM:

In [11]:
import numpy as np

X = np.random.random((5, 5))           # random 5x5 ndarray (5 rows at columns)

X_normalized = (X - X.mean()) / X.std()     # normalization process (formula = subtract mean sa each elements tas divide sa sd)

np.save("X_normalized.npy", X_normalized)   # saves normalized array as .npy

print("Original Array:\n", X)
print("\nNormalized Array:\n", X_normalized)

Original Array:
 [[0.45863091 0.05449412 0.38320267 0.23937585 0.02162464]
 [0.71973644 0.90737304 0.82713924 0.85869215 0.56525697]
 [0.45362452 0.2744174  0.52302925 0.67169798 0.30435298]
 [0.00522155 0.33692658 0.76417718 0.98547387 0.83003455]
 [0.76131642 0.79698092 0.19061577 0.05624348 0.01285694]]

Normalized Array:
 [[-0.06860198 -1.35998483 -0.30962615 -0.76921183 -1.4650163 ]
 [ 0.76573734  1.36531324  1.10893336  1.20975784  0.27211206]
 [-0.08459942 -0.65723972  0.13717716  0.61223474 -0.56158324]
 [-1.51743089 -0.45749723  0.90774372  1.61487744  1.11818505]
 [ 0.89860244  1.01256513 -0.92502031 -1.35439491 -1.49303271]]


DIVISIBLE BY 3 PROBLEM:

In [8]:
import numpy as np

A = np.arange(1, 101)**2          # squares of first 100 integers (arange pero walang interval)
A = A.reshape(10, 10)             # reshapes array into 10x10 (10 rows at columns)

div_by_3 = A[A % 3 == 0]          # get elements na divisible by 3 lang

np.save("div_by_3.npy", div_by_3)  # save as .npy

print("10x10 Array:\n", A)
print("\nDivisible by 3:\n", div_by_3)

10x10 Array:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

Divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
